---
title: "P8105_hw1_jl5172"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)

```


```{r echo=TRUE}
#A random sample of size 10 from a uniform[0, 5] distribution
#the runif function provide information about the uniform distribution on the interval from min to max. In this case #sample size is 10,min=0 max=5 
#A logical vector indicating whether elements of the sample are greater than 2
#compare each elements in vector compare2 to 2 one by one. If an element is greater than 2 R will return TRUE otherwise it will return FALSE
#A (length-10) character vector 
#A (length-10) factor vector
# the vector named student contains set of numeric codes with character-valued levels
library(tidyverse)
set.seed(1)
dataframe1=tibble(
random10=runif(10,0,5),  
logical2=c(random10>2),character10=c("a","b","c","d","e","f","g","h","i","j"),
factor10=factor(c(1,0,1,1,0,1,0,0,1,1),levels = c(0,1),labels = c("male","female")))

mean(dataframe1$random10)
mean(dataframe1$logical2)
mean(dataframe1$character10)
mean(dataframe1$factor10)

# According to the output. Mean can be taken from random10(numeric) and logical2(numeric) 
#but not character10(character) and factor10(factor) since mean function is designed for numeric/logical vectors


```

```{r}

```

```{r}
as.numeric(dataframe1$logical2)
as.numeric(dataframe1$character10)  
as.numeric(dataframe1$factor10)
# the factor vector and logical vector have been successfully converted to numeric. However, character vector was not able to be converted
```

```{r}
character10<-as.factor(dataframe1$character10)
character10<-as.numeric(character10)
# the character vector has been sucessfully converted to numeric.
factor10<-as.character(dataframe1$factor10)
factor10<-as.numeric(factor10)
# Warning message is shown. "NAs introduced by coercion"
```



## inline code
```{r}
library(tidyverse)
set.seed(1)

dataframe2 = tibble(
x = rnorm(1000, sd =1),
y = rnorm(1000,sd =1),
logicxy = c((x+y)>0),
numericxy=as.numeric(logicxy),
factorxy=as.factor(logicxy))
```

The mean of x is `r mean(dataframe2$x)`
The median of x is `r median(dataframe2$x)`
The proportion of cases for which logical vector is TRUE is `r sum(dataframe2$logicxy)`

Scatterplot Logical Variable
```{r}
library(ggplot2)
first_plot=ggplot(dataframe2, aes(x = dataframe2$x, y = dataframe2$y,color=dataframe2$logicxy)) + geom_point()

ggsave("firstplot.pdf",plot =first_plot )
```

Scatterplot Numeric variable
```{r}
ggplot(dataframe2, aes(x = dataframe2$x, y = dataframe2$y,color=dataframe2$numericxy)) + geom_point()

```

Scatterplot Factor variable
```{r}
ggplot(dataframe2, aes(x = dataframe2$x, y = dataframe2$y,color=dataframe2$factorxy)) + geom_point()
```



